#cloud-config
package_update: true
package_upgrade: true

packages:
  - nginx
  - htop
  - unzip
  - curl
  - git

write_files:
  - owner: www-data:www-data
    path: /var/www/html/index.html
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Azure Showcase - ${vm_name}</title>
          <style>
              body { font-family: Arial, sans-serif; margin: 40px; background-color: #f0f0f0; }
              .container { background-color: white; padding: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
              .header { color: #0078d4; border-bottom: 2px solid #0078d4; padding-bottom: 10px; }
              .info { margin: 20px 0; }
              .status { background-color: #d4edda; color: #155724; padding: 10px; border-radius: 5px; margin: 10px 0; }
          </style>
      </head>
      <body>
          <div class="container">
              <h1 class="header">Senior System Engineer Showcase</h1>
              <div class="status">✅ Server is running successfully</div>
              <div class="info">
                  <h3>Server Information:</h3>
                  <ul>
                      <li><strong>Hostname:</strong> ${vm_name}</li>
                      <li><strong>Platform:</strong> Azure</li>
                      <li><strong>Deployment:</strong> Terraform Infrastructure as Code</li>
                      <li><strong>Load Balancer:</strong> Azure Load Balancer</li>
                      <li><strong>Security:</strong> Network Security Groups + Key Vault</li>
                  </ul>
              </div>
              <div class="info">
                  <h3>Technologies Demonstrated:</h3>
                  <ul>
                      <li>Azure Cloud Infrastructure</li>
                      <li>Terraform IaC</li>
                      <li>Microsoft 365 Integration</li>
                      <li>Enterprise Security Practices</li>
                      <li>Automated Deployment</li>
                  </ul>
              </div>
          </div>
      </body>
      </html>

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - ufw --force enable
  - ufw allow 80
  - ufw allow 443
  - ufw allow 22
  - echo "$(date): Cloud-init completed on ${vm_name}" >> /var/log/deployment.log
